name: Build and deploy ASP.Net Core app to Azure Web App - mzansi-builds-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # We can keep the build on Linux (it's faster/cheaper)
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: dotnet restore
        run: dotnet restore src/mzansi-builds-api/mzansi-builds-api.csproj

      - name: Build with dotnet
        run: dotnet build src/mzansi-builds-api/mzansi-builds-api.csproj --configuration Release --no-restore

      - name: dotnet publish
        run: dotnet publish src/mzansi-builds-api/mzansi-builds-api.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest # CHANGED: Using Windows runner for a Windows App Service is often more reliable
    needs: build
    permissions:
      id-token: write 
      contents: read 

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish 
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_045AD78B2A1B43B29EAF9B6A7F013F9C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DF32009502534E7884E670FA65ED5DD4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4BAA1A02B1104238896830028947143F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mzansi-builds-api'
          # No slot-name needed unless you explicitly created one
          package: ./publish
